<?php 
return [
   "booking_modal" => "", 
   "booking_enable_captcha" => "", 
   "booking_card_accepted" => [
   ], 
   "booking_currency" => [
      [
         "title" => "INR", 
         "name" => "INR", 
         "symbol" => "₹", 
         "rate" => "82.14", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => "", 
         "booking_currency_precision" => "", 
         "country" => "IN" 
      ], 
      [
         "title" => "USD", 
         "name" => "USD", 
         "symbol" => "$", 
         "rate" => "0.012", 
         "booking_currency_pos" => "right", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "US" 
      ], 
      [
         "title" => "EUR", 
         "name" => "EUR", 
         "symbol" => "€", 
         "rate" => "0.012", 
         "booking_currency_pos" => "right", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "EU" 
      ], 
      [
         "title" => "AUD", 
         "name" => "AUD", 
         "symbol" => "$", 
         "rate" => "0.019", 
         "booking_currency_pos" => "right", 
         "currency_rtl_support" => "", 
         "thousand_separator" => ",", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "AU" 
      ], 
      [
         "title" => "CAD", 
         "name" => "CAD", 
         "symbol" => "$", 
         "rate" => "0.016", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "CA" 
      ], 
      [
         "title" => "JPY", 
         "name" => "JPY", 
         "symbol" => "¥", 
         "rate" => "1.78", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "JP" 
      ], 
      [
         "title" => "KPW", 
         "name" => "KPW", 
         "symbol" => "₩", 
         "rate" => "10.98", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "KR" 
      ], 
      [
         "title" => "KRW", 
         "name" => "KRW", 
         "symbol" => "₩", 
         "rate" => "17.00", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "KR" 
      ], 
      [
         "title" => "AFN", 
         "name" => "AFN", 
         "symbol" => "؋", 
         "rate" => "1.06", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "AF" 
      ], 
      [
         "title" => "DZD", 
         "name" => "DZD ", 
         "symbol" => "دج", 
         "rate" => "1.71", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => "", 
         "booking_currency_precision" => "", 
         "country" => "DZ" 
      ], 
      [
         "title" => "ALL", 
         "name" => "ALL", 
         "symbol" => "L", 
         "rate" => "1.43", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "AL" 
      ], 
      [
         "title" => "BND", 
         "name" => "BND", 
         "symbol" => "$", 
         "rate" => "0.017", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "BN" 
      ], 
      [
         "title" => "HUF", 
         "name" => "HUF", 
         "symbol" => "Ft", 
         "rate" => "4.90", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "HU" 
      ], 
      [
         "title" => "BRL", 
         "name" => "BRL", 
         "symbol" => "R$", 
         "rate" => "0.06", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "BR" 
      ], 
      [
         "title" => "BGN", 
         "name" => "BGN", 
         "symbol" => "лв", 
         "rate" => "0.023", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "BG" 
      ], 
      [
         "title" => "DKK", 
         "name" => "DKK", 
         "symbol" => "kr", 
         "rate" => "0.091", 
         "booking_currency_pos" => "left", 
         "currency_rtl_support" => "", 
         "thousand_separator" => "", 
         "decimal_separator" => ".", 
         "booking_currency_precision" => 2, 
         "country" => "DK" 
      ] 
   ], 
   "booking_primary_currency" => "INR", 
   "is_guest_booking" => "off", 
   "st_booking_enabled_create_account" => "on", 
   "guest_create_acc_required" => "off", 
   "use_woocommerce_for_booking" => "on", 
   "woo_checkout_show_shipping" => "on", 
   "st_woo_cart_is_collapse" => "on", 
   "tax_enable" => "", 
   "st_tax_include_enable" => "", 
   "tax_value" => "", 
   "booking_fee_enable" => "off", 
   "booking_fee_amount" => "", 
   "booking_tab" => "", 
   "st_site_key_captcha" => "", 
   "st_secret_key_captcha" => "", 
   "booking_currency_conversion" => [
      [
         "title" => "INR", 
         "name" => "INR", 
         "rate" => "82.14" 
      ] 
   ], 
   "woocommerce_tab" => "", 
   "tax_tab" => "", 
   "booking_fee_tab" => "", 
   "booking_fee_type" => "" 
]; 

